from ploceidae.dependency_graph_manager import DependencyGraphManager
from ploceidae.dependency_graph_manager.dependency_graph import DependencyGraph

DEPENDENCY_GRAPH_MANAGER = DependencyGraphManager(DependencyGraph())
