name: Merge To Develop

# Controls when the action will run (on push to develop; in our case, this should only ever be a merge)
on:
  pull_request:
    types: [closed]
    branches: [develop]

# Only one instance of this workflow can run at a time. Also locks out daily-develop-build (this is so our history is kept tidy)
# if we want to just lock this workflow use ${{ github.workflow }} instead of develop-lock
concurrency:
    group: develop-lock

jobs:
  # build our project
  build:
    if: github.event.pull_request.merged == true

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Run after merge to develop
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: run pytest
        run: pytest ploceidae/unit_tests

      # TODO: make sure in the case that a person has a different version.txt (i.e. they are lagging behind), that git raises a merge conflict and the version does not get compromised
      # increment version number based on the change type
      - name: increment version
        run: git log -1 --format=%f | tr - " " | awk '{print $8}' | xargs ./build_scripts/increment_version_number.py ${version_increment}

      # writing my own commit step and not using existing commit actions because those actions change the author. I want to preserve the commit as is (except for the version.txt)
      - name: add commit
        run: |
            git config --global user.name $(git log -1 --format=%an)
            git config --global user.email $(git log -1 --format=%ae)
            git add version.txt
            git commit -m "version increment for $(git log -1 --format=%b)"
            git push -f

      
